# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iziCMSapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userroleonsite',
            old_name='choice_text',
            new_name='isAdmin',
        ),
    ]
