# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iziCMSapp', '0002_auto_20170222_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='userroleonsite',
            name='isAdmin',
        ),
        migrations.AddField(
            model_name='site',
            name='FTPHost',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='site',
            name='FTPId',
            field=models.CharField(default='127.0.0.1', max_length=200),
        ),
        migrations.AddField(
            model_name='site',
            name='FTPPort',
            field=models.IntegerField(default=21),
        ),
        migrations.AddField(
            model_name='page',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iziCMSapp.Site'),
        ),
    ]
