# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 12:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iziCMSapp', '0003_auto_20170227_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userroleonsite',
            name='site',
        ),
        migrations.RemoveField(
            model_name='userroleonsite',
            name='user',
        ),
        migrations.AddField(
            model_name='page',
            name='link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='page',
            name='selector',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='site',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='page',
            name='path',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='UserRoleOnSite',
        ),
    ]
