# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iziCMSapp', '0004_auto_20170227_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='selector',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='FTPId',
            field=models.CharField(default='', max_length=200),
        ),
    ]
