# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iziCMSapp', '0006_auto_20170306_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='FTPHost',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
