# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iziCMSapp', '0008_auto_20170306_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='FTPPort',
            new_name='ftp_port',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='FTPId',
            new_name='ftp_user',
        ),
        migrations.RemoveField(
            model_name='site',
            name='FTPHost',
        ),
        migrations.AddField(
            model_name='site',
            name='ftp_host',
            field=models.CharField(default='', max_length=200),
        ),
    ]
