# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iziCMSapp', '0009_auto_20170322_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='link',
        ),
        migrations.RemoveField(
            model_name='site',
            name='users',
        ),
        migrations.AlterUniqueTogether(
            name='site',
            unique_together=set([('ftp_host', 'ftp_user')]),
        ),
    ]
