# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iziCMSapp', '0010_auto_20170327_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='link',
            field=models.URLField(default=''),
        ),
    ]
