# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iziCMSapp', '0011_page_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='link',
        ),
        migrations.AlterField(
            model_name='page',
            name='selector',
            field=models.CharField(default='body', max_length=200),
        ),
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='site',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='site',
            name='name',
        ),
    ]
