# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iziCMSapp', '0012_auto_20170411_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='url',
            new_name='hostname',
        ),
    ]
