# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iziCMSapp', '0015_auto_20170411_2259'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set([('site', 'path')]),
        ),
    ]
