# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iziCMSapp', '0016_auto_20170411_2337'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set([('site', 'path', 'selector')]),
        ),
    ]
